# Site settings
title: Lisa Halvorsen
email: halvorsen.lisa@gmail.com
description: 
baseurl: "https://lha047.github.io/" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  lha047

# Build settings
markdown: kramdown
